### ISSUE TITLE
您好，您这个有demo可供参考吗

### ISSUE THREAD

**Issue by fanly** [fouber/fis-parser-handlebars#2]
如题，在配置文件中是怎么配置的呢？谢谢

**Comment by fouber** [comment]
@fanly 

### 1. 安装插件：

> npm install -g fis-parser-handlebars

### 2. 配置

``` js
// fis-conf.js
fis.config.set('modules.parser.handlebars', 'handlebars');
fis.config.set('project.fileType.text', 'handlebars');
fis.config.set('roadmap.ext.handlebars', 'js');
```

**Comment by fanly** [comment]
谢谢您，那这个模板代码怎么写呢？js怎么调用它，如何传递参数进去呢，谢谢~~~

**Comment by fanly** [comment]
我QQ249932635，能直接向您请教吗？谢谢

**Comment by fouber** [comment]
@fanly 

假设你有一个foo.handlebars的模板文件，其中的内容是：

``` hanblebars
<div class="entry">
  <h1>{{title}}</h1>
  <div class="body">
    {{body}}
  </div>
</div>
```

然后你再写一个叫foo.js的js文件，内容是：

``` js
var tpl = __inline('foo.handlebars');
var context = {title: "My New Post", body: "This is my first post!"};
var html = console.log(tpl(context));
console.log(html);
```

记得在页面上使用handlebars的 [runtime版本](http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars.runtime-v3.0.3.js) 作为运行时框架。

**Comment by fanly** [comment]
@fouber 
我这老提示这个错误： [ERROR] unable to load plugin [fis-parser-handlebars]
怎么回事呢？

**Comment by fouber** [comment]
没有 `-g` 安装吧

**Comment by fanly** [comment]
现在出现这个问题了Uncaught Error: Unknown template object: function
Handlebars.template(function (Handlebars,depth0,helpers,partials,data) {

**Comment by fouber** [comment]
@fanly 
有没有在页面上引入 runtime 版的handlebars.js框架啊，我在之前的几个回复中提到了的

**Comment by fanly** [comment]
@fouber 木有问题了，谢谢您~
