### ISSUE TITLE
npm 上的 fis-parser-handlebars-3.x 是否将源码和文档合并

### ISSUE THREAD

**Issue by nimoc** [fouber/fis-parser-handlebars#4]
https://www.npmjs.com/package/fis-parser-handlebars-3.x

有些人平时用的是 3.0 。可否在本项目创建 branch: **fis-parser-handlebars-3.x**
并在 master 的 README.md 中加上 3.x 分支的 README.md 链接 https://github.com/fouber/fis-parser-handlebars/tree/3.x

**Comment by fouber** [comment]
@nimojs 

https://github.com/scrat-team/fis-parser-handlebars-3.x
